// <auto-generated />
using System;
using CarbonForm.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonForm.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123163823_EntityUpdate")]
    partial class EntityUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarbonForm.Core.Entities.Consumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClothingExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CosmeticExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EatingOutFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("ElectronicsExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LocalProductPreferenceScore")
                        .HasColumnType("int");

                    b.Property<decimal>("MeatConsumptionKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersonalCareExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VeggieConsumptionKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("Consumptions");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.HomeEnergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AirConditionerType")
                        .HasColumnType("int");

                    b.Property<int>("AirConditionerUseDays")
                        .HasColumnType("int");

                    b.Property<int>("CarWashCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ElectricityBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ElectricityKwh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasAirConditioner")
                        .HasColumnType("bit");

                    b.Property<decimal>("LpgM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NaturalGasBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NaturalGasM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SolidWasteKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WaterBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterM3")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("HomeEnergies");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.Transportation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarTravelCount")
                        .HasColumnType("int");

                    b.Property<int>("CarTravelKm")
                        .HasColumnType("int");

                    b.Property<int>("CommuteDistanceKm")
                        .HasColumnType("int");

                    b.Property<int>("CommuteType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightDomesticCount")
                        .HasColumnType("int");

                    b.Property<int>("FlightDomesticKm")
                        .HasColumnType("int");

                    b.Property<int>("FlightInternationalCount")
                        .HasColumnType("int");

                    b.Property<int>("FlightInternationalKm")
                        .HasColumnType("int");

                    b.Property<int>("PublicTransportTravelCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicTransportTravelKm")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("Transportations");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AgeRange")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DoCompost")
                        .HasColumnType("bit");

                    b.Property<bool>("DoRecycle")
                        .HasColumnType("bit");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GreenFairName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAttendedGreenFair")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPlantedTree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNgoMember")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TreeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.Consumption", b =>
                {
                    b.HasOne("CarbonForm.Core.Entities.Survey", "Survey")
                        .WithOne("Consumption")
                        .HasForeignKey("CarbonForm.Core.Entities.Consumption", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.HomeEnergy", b =>
                {
                    b.HasOne("CarbonForm.Core.Entities.Survey", "Survey")
                        .WithOne("HomeEnergy")
                        .HasForeignKey("CarbonForm.Core.Entities.HomeEnergy", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.Transportation", b =>
                {
                    b.HasOne("CarbonForm.Core.Entities.Survey", "Survey")
                        .WithOne("Transportation")
                        .HasForeignKey("CarbonForm.Core.Entities.Transportation", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.UserInfo", b =>
                {
                    b.HasOne("CarbonForm.Core.Entities.Survey", "Survey")
                        .WithOne("UserInfo")
                        .HasForeignKey("CarbonForm.Core.Entities.UserInfo", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("CarbonForm.Core.Entities.Survey", b =>
                {
                    b.Navigation("Consumption");

                    b.Navigation("HomeEnergy");

                    b.Navigation("Transportation");

                    b.Navigation("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
